language: node_js
sudo: required
dist: trusty
node_js:
  - "7"
env:
  - CXX=g++-4.8
#  - LAIKA_OPTIONS="-t 5000"
services:
  - mongodb
  - docker

before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
  - npm install -g node-gyp
  - cd app
  - npm install --save babel-runtime react react-dom react-router ramda radium react-swipe fluture react-contenteditable leaflet
install:
  - npm install --production
  
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
script: 
  - meteor build --allow-superuser --directory ../mrt_build --server-only
  - ls -l ../mrt_build
after_success:
  - cd .. ; docker build -f Dockerfile -t testtag .
