version: '2'
services:
  db:
    restart: always
    image: mongo:3.4.0
    volumes:
      - /usr/share/commonbike_mdb:/data/db
    ports:
      - localhost:4001:27017

  app:
    restart: always
    image: commonbike:latest
    environment:
     - METEOR_SETTINGS=##_METEOR_SETTINGS_##
    links:
      - db:db
    ports:
      - localhost:4000:80
