version: '2'
services:
  db:
    restart: always
    image: mongo:3.4.0
    volumes:
      - /usr/share/commonbike_mdb:/data/db
    ports:
      - localhost:4001:27017

  app:
    restart: always
    image: commonbike:latest
    environment:
      - 'METEOR_SETTINGS={"mapbox":{"style":"mapbox.streets","accessToken":"pk.eyJ1IjoiZXJpY3ZycCIsImEiOiJjaWhraHE5ajIwNmRqdGpqN2h2ZXhqMnRsIn0.1FBWllDyQ_nSlHFE2jMLDA"},"private":{"testdata":{"cleanupusers":false,"cleanupother":false,"insert":false,"log":false},"slack":{"notify":true,"address":"https://hooks.slack.com/services/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","channel":"commonbike-bot","name":"commonbike-bot"}}}'
    links:
      - db:db
    ports:
      - localhost:4000:80
